### ISSUE TITLE
Using Google embeddings

### ISSUE THREAD

**Issue by wbecker** [src-d/wmd-relax#12]
Hey, great project!

I don't quite understand what embeddings it uses in the spacy example. How do you use "GoogleNews-vectors-negative300.bin.gz", as Matt Kusner uses? Or is it using this already?

**Comment by vmarkovtsev** [comment]
Thanks! It should automatically use whatever vectors attached to spacy's nlp object. In my tests, "it just worked".

**Comment by vmarkovtsev** [comment]
Of course, if your goal is to calculate "one to many", you have to write the custom adapters, e.g. https://github.com/src-d/wmd-relax/blob/master/spacy_example.py

**Comment by wbecker** [comment]
Ah I think this line is the key: https://github.com/src-d/wmd-relax/blob/master/spacy_example.py#L38

**Comment by wbecker** [comment]
So spacy already manages this itself - that must have happened when I did the spacy install. Makes sense!

**Comment by vmarkovtsev** [comment]
Yep, or this one: https://github.com/src-d/wmd-relax/blob/master/wmd/__init__.py#L635

**Comment by wbecker** [comment]
And this is what spacy says: https://spacy.io/docs/usage/word-vectors-similarities

**Comment by wbecker** [comment]
Makes sense, thanks! I'll have a play now that I understand it :)

**Comment by wbecker** [comment]
Thanks for implementing the kNN optimisations btw! Glad I don't have to do it myself!
