### ISSUE TITLE
Pruning checking wrong neighbour?

### ISSUE THREAD

**Issue by wbecker** [src-d/wmd-relax#19]
In the [WMD paper](http://www.cs.cornell.edu/~kilian/papers/wmd_metric.pdf), it says that: "...we first check if the RWMD lower bound exceeds the distance of the current  k-th closest document, if so we can prune it."

I assume that this is happening [here](https://github.com/src-d/wmd-relax/blob/master/wmd/__init__.py#L553), where the code is: ` farthest = -neighbors[0][0]`. 

This seems to be checking the closest element, not the k-th closest. 

Am I reading this wrong? Is it sorted in reverse perhaps somehow, or is this not that check?

**Comment by wbecker** [comment]
I don't understand why the value is negated everywhere as well. Might be nice to put in a comment or something?

**Comment by vmarkovtsev** [comment]
Yep, everything's fine here. The built-in heap is the min heap, so I have to invert the values and pick the smallest -> that is, the largest.

**Comment by wbecker** [comment]
Ah, that's this line here: https://github.com/src-d/wmd-relax/blob/master/wmd/__init__.py#L531

**Comment by wbecker** [comment]
So you use that to keep track of the smallest distances. Makes sense!
