### ISSUE TITLE
Type Error on Item Identifiers in Vocabulary Optimizer

### ISSUE THREAD

**Issue by wzamlynny** [src-d/wmd-relax#20]
Current documentation does not require the item identifiers to be contained in a numpy array, however the Vocabulary Optimizer throws an error on certain documents if they are not. 
In particular, on line 93 in \_\_call__ of TailVocabularyOptimizer. The error I encounter is:

`TypeError: only integer scalar arrays can be converted to a scalar index`

I noticed that further up in the Vocabulary Optimizer (line 66-69), the identifiers are cast to a numpy array within a try-catch, should this be the case for this logical branch as well? I have confirmed that doing a try catch with the cast does prevent this error from coming up in my use case.

**Comment by vmarkovtsev** [comment]
Thanks for reporting this! Surely this is a bug. Can you please test if https://github.com/src-d/wmd-relax/commit/da0ba0421fe503e5ed447544831235f23f3b9c33 fixes the problem?

**Comment by wzamlynny** [comment]
Yes, it appears to be fixed now. Thank you!
