### ISSUE TITLE
Numpy floating point precision causes SpaCy vocab KeyValue error

### ISSUE THREAD

**Issue by Dennett** [src-d/wmd-relax#21]
If you have a `token` in your `nlp(text)` whose `token.orth` is a very large int (for example: `886050111519832510`), then in `WMD._common_vocabulary_batch`, `numpy.concatenate((words1, words2))` will approximate those integers in `joint, index = numpy.unique(numpy.concatenate((words1, words2)), return_index=True)`, thereby returning incorrect/invalid vocabulary keys for `evec = self.embeddings[joint]` in `WMD._estimate_WMD_relaxation_batch`.

```python
ipdb> 886050111519832510 in words1
True
ipdb> 886050111519832510 in words2
True
ipdb> 886050111519832510 in numpy.concatenate((words1, words2))
False
```

This last false occurs because 886050111519832510 has been rounded to 886050111519832448 as a numpy.float.

A hack solution is to use strings, or something more immutable.
```python
    def _common_vocabulary_batch(self, words1, weights1, i2):
        words2, weights2 = self._get_vocabulary(i2)
        words1_np = numpy.array(words1, dtype=numpy.str)
        words2_np = numpy.array(words2, dtype=numpy.str)
        joint, index = numpy.unique(numpy.concatenate((words1_np, words2_np)),
                                    return_index=True)
        nw1 = numpy.zeros(len(joint), dtype=numpy.float32)
        cmp = index < len(words1)
        nw1[numpy.nonzero(cmp)] = weights1[index[cmp]]
        nw2 = numpy.zeros(len(joint), dtype=numpy.float32)
        nw2[numpy.searchsorted(joint, words2)] = weights2
        return joint, nw1, nw2
```

Then convert back to int when querying for the appropriate SpaCy vectors.
```python
# Hook in WMD
class SpacyEmbeddings(object):
    def __getitem__(self, item):
        return nlp.vocab[int(item)].vector
```

**Comment by vmarkovtsev** [comment]
Thanks for reporting! I think I fixed this, could you please verify.

**Comment by Dennett** [comment]
Sorry for the delay in responding. Flu season here. 

I uninstalled and pulled your changes, then reinstalled.

For reference, I am using:
```python
nlp = spacy.load('en_core_web_md')
```
and am now getting:
```
line 372, in _get_vocabulary words = numpy.array(words, dtype=numpy.int64)
OverflowError: Python int too large to convert to C long
```

However, it will work with the silly string hack:
```python
        if not isinstance(words, numpy.ndarray):
            try:
                words = numpy.array(words, dtype=numpy.int64)
            except OverflowError:
                words = numpy.array(words, dtype=numpy.str)
```

Of course, I have to convert back...
```python
class SpacyEmbeddings(object):
    def __getitem__(self, item):
        return nlp.vocab[int(item)].vector
```

**Comment by vmarkovtsev** [comment]
Can you please post an example text?

**Comment by vmarkovtsev** [comment]
Does this code work for you? Works for me, but my platform is 64 bit:

```
numpy.array([886050111519832510], dtype=numpy.int64)
```

**Comment by Dennett** [comment]
Yeah, that value works for me too. I'm using `Python 3.6.2` on a 2017 64-bit MacBook.  So maybe consider the original float rounding problem fixed, but I think there might be a second problem now if you want to be compatible with SpaCy embeddings. Unless I've an unusually small `sys.maxsize`. 

As for sample text, here's one word that gives me trouble.

```python
nlp('Moscow')[0].orth
Out[14]: 13549936205470267463
```
Note this is larger than my `sys.maxsize`:

```python
import sys
sys.maxsize
Out[4]: 9223372036854775807
```

And so I get `Traceback (most recent call last):
OverflowError: Python int too large to convert to C long` when trying to run:

```python
np.array([13549936205470267463], dtype=np.int64)
```

For reference:
```python
import spacy
spacy.__version__
Out[15]: '2.0.3'
```

And I'm using: 
```python
nlp = spacy.load('en_core_web_md')
```

**Comment by vmarkovtsev** [comment]
Thanks. Now I see the problem. dtype must be `uint64`. Issuing the fix.

**Comment by vmarkovtsev** [comment]
`v1.2.8` published.
