### ISSUE TITLE
spacy pipeline not triggering wmd-relax similarity function

### ISSUE THREAD

**Issue by engrut** [src-d/wmd-relax#26]
I am using WMD-relax with spacy. However, using the following does not trigger the WMD-relax similarity function and still uses the spacy similarity function. 

```
import spacy
import wmd

nlp = spacy.load('en', create_pipeline=wmd.WMD.create_spacy_pipeline)
doc1 = nlp("Politician speaks to the media in Illinois.")
doc2 = nlp("The president greets the press in Chicago.")
print(doc1.similarity(doc2))

```
It produces exactly the same similarity measures which spacy normal similarity function does and also triggers this function:

```
 def similarity(self, other):
        """
        Compute a semantic similarity estimate. Defaults to cosine over vectors.
        Arguments:
            other:
                The object to compare with. By default, accepts Doc, Span,
                Token and Lexeme objects.
        Returns:
            score (float): A scalar similarity score. Higher is more similar.
        """
        if 'similarity' in self.doc.user_token_hooks:
                return self.doc.user_token_hooks['similarity'](self)
        if self.vector_norm == 0 or other.vector_norm == 0:
            return 0.0
        return numpy.dot(self.vector, other.vector) / (self.vector_norm * other.vector_norm)
```

For now, I am using the following as a workaround which works fine. 
```
wmd_instance = SpacySimilarityHook(nlp)
wmd_instance.compute_similarity(doc1, doc2).  # it returns the distance

```
Any ideas why the pipeline isn't triggering the wmd-relax similarity function?

Another thing which I observed is that it doesn't run on certain CPU unless built from source. It's a minor thing.

**Comment by vmarkovtsev** [comment]
Looks like 2.0 changed the behavior, investigating

**Comment by vmarkovtsev** [comment]
Relates to https://github.com/src-d/wmd-relax/issues/3

**Comment by vmarkovtsev** [comment]
Yep, [2.0 changed API](https://spacy.io/usage/processing-pipelines) and I need to rewrite the integration from scratch :-)

**Comment by engrut** [comment]
ahh okay :) Is it possible to also know which processors aren't compatible with compute_similarity function? As we got an error while running our dockerized application on a production server though it worked fine on our local machines. We had to build the wm-relax from the source on that machine to resolve the issue. If its possible, I can open a separate issue for this.

**Comment by vmarkovtsev** [comment]
I think it uses modern CPU features in the binary package on PyPi. The reason is `-march=native` in https://github.com/src-d/wmd-relax/blob/master/CMakeLists.txt#L23 Most likely those instructions are AVX/AVX2. You can inspect the difference in `lscpu | grep Flags`

**Comment by engrut** [comment]
These two flags aren't available on our prototyping server so maybe that's the reason. I expect that the absence of these flags will make the computing similarity way slower.

**Comment by CecGreg** [comment]
Have this question been solved?

**Comment by vmarkovtsev** [comment]
Nopes, no time to work on this, PRs welcome.

**Comment by IlyasYOY** [comment]
I've found a workaround:

1. You need to change `__call__` method in `SpacySimilarityHook`

```python 
        def __call__(self, doc):
            doc.user_hooks["similarity"] = self.compute_similarity
            doc.user_span_hooks["similarity"] = self.compute_similarity
            return doc
```

2. Then you can use this hook like this:

```python
import spacy

import wmd
from spacy.language import Language
from spacy.tokens.doc import Doc


def main():
    nlp: Language = spacy.load('en_core_web_md')
    nlp.add_pipe(wmd.WMD.SpacySimilarityHook(nlp), last=True)
    print(nlp.pipe_names)

    wmd_instance = wmd.WMD.SpacySimilarityHook(nlp)

    doc1: Doc = nlp("Politician speaks to the media in Illinois.")
    doc2: Doc = nlp("The president greets the press in Chicago.")

    print(doc1.similarity(doc2))
    print(wmd_instance.compute_similarity(doc1, doc2))


if __name__ == '__main__':
    main()
``` 

Output: 
```text
['tagger', 'parser', 'ner', 'SpacySimilarityHook']
4.08184289932251
4.08184289932251
```

Added these changes in PR #42
