### ISSUE TITLE
Looks nice! Question and idea

### ISSUE THREAD

**Issue by honnibal** [src-d/wmd-relax#3]
Hey,

Thanks for the spaCy integration --- this looks nice! I've actually been thinking about WMD lately.

I'm hoping you can answer a question for me. I honestly have trouble understanding the EMD paper, so I've never been sure I've understood WMD correctly. The following implementation seemed to match results from the pyemd library. I'm wondering whether you can tell me whether it's correct.

```python
def word_movers_similarity(doc1, doc2, sim_metric=None):
    if sim_metric is None:
        sim_metric = cosine_similarity

    doc1 = [t for t in doc1 if t.has_vector]
    doc2 = [t for t in doc2 if t.has_vector]
    N1 = len(doc1)
    N2 = len(doc2)
    similarities = np.zeros((N1, N2))
    for i in range(N1):
        vec1 = doc1[i].vector / doc1[i].vector_norm
        for j in range(N2):
            vec2 = doc2[j].vector / doc2[j].vector_norm
            similarities[i, j] = sim_metric(vec1, vec2)
    print(similarities)
    flows1 = similarities.argmax(axis=0)
    flows2 = similarities.argmax(axis=1)
    sim = (similarities.max(axis=0).sum() + similarities.max(axis=1).sum()) / (N1+N2)
    return sim, flows1, flows2
```

All this does is compute a similarity matrix, and then take the column and row maximums, which represent the nearest similarity for each word in the other document. We then take the average of these similarities.

Is this correct? Usually EMD is described as solving this linear system, and I've honestly never taken a linear algebra class...So that explanation leaves me confused.

Secondly: you might be interested in over-writing the default `.similarity()` hook for the document, using the WMD similarity. You can do that as follows:

```python

class SpacySimilarityHook(object):
    def __init__(self, *args, **kwargs):
        pass # Whatever you need here

    def __call__(self, doc):
        doc.user_hooks['similarity'] = self.compute_similarity
        doc.user_span_hooks['similarity'] = self.compute_similarity

    def compute_similary(self, doc1, doc2):
        # Compute similarity here
        return 0.23

def create_pipeline(nlp):
    return [nlp.tagger, nlp.parser, SpacySimilarityHook(nlp)]

def example():
    nlp = spacy.load('en', create_pipeline=create_pipeline)
    doc1 = nlp(u'Example document')
    doc2 = nlp(u'Second example')
    assert doc1.similarity(doc2) == 0.23
```

The `create_pipeline` hook isn't strictly necessary. You could just append the instance to `nlp.pipeline` at some point, to run the callable by default when processing documents.

**Comment by vmarkovtsev** [comment]
Hey, thanks for the suggestion! Will rewrite it now.

As for WMD, I am afraid this is not correct. I've recently had a blog post which may be of some use: https://blog.sourced.tech/post/lapjv/ That post is not exactly on the topic but still has smth about EMD/WMD.

How about arranging a Skype call, this is going to be long.

**Comment by vmarkovtsev** [comment]
Hehe, rewrite using the similarity hook is fun but it will not solve the real word nearest neighbors problem. The thing is, given millions of documents, the similarity calculation pipeline is not linear. It has two clever tricks.

**Comment by vmarkovtsev** [comment]
Regarding pyemd, EMD problem has the exact solution, so any implementation must match the reference bit to bit.
