### ISSUE TITLE
item identifiers

### ISSUE THREAD

**Issue by Bachstelze** [src-d/wmd-relax#30]
What means the item identifier for the nbow-definition in the usage example? I'm confused because the arrays are the same.

**Comment by vmarkovtsev** [comment]
Hey @Bachstelze 

As written a few lines below,

> The first element is the human-readable name of the sample, the second is an iterable with item identifiers and the third is numpy.ndarray with the corresponding weights.

That is, "first" and "second" are used as keys and "#1" and "#2" are used as descriptions (proper sample names).
