### ISSUE TITLE
MemoryError when vocab contains words with numbers

### ISSUE THREAD

**Issue by zdk123** [src-d/wmd-relax#49]
I've stumbled on a weird edge case where I am getting a MemoryError even on small vectors. I've narrowed it down to my special case where I need to represent words as a label + integers (e.g. Word01, Word02, ...)

I've included data (below) that reproduces the error on MacOSx, python 3.7 with wmd==1.3.0 and spacy==2.1.3.

```
## Word01, Word02, ...
python -m spacy init-model xx spacy.word2vec.model --vectors-loc word2vec.txt
## A, B, C, ...
python -m spacy init-model xx spacy.word2vec2.model --vectors-loc word2vec2.txt
```

python:
```
import spacy
import wmd

nlp1 = spacy.load('./spacy.word2vec.model')
nlp2 = spacy.load('./spacy.word2vec2.model')

## equivilent
doc1 = nlp1(u"Word01")
doc2 = nlp1(u"Word02")
print(doc1.similarity(doc2))

doc1 = nlp2(u"A")
doc2 = nlp2(u"B")
print(doc1.similarity(doc2))

## WMD case
nlp1.add_pipe(wmd.WMD.SpacySimilarityHook(nlp1), last=True)
nlp2.add_pipe(wmd.WMD.SpacySimilarityHook(nlp2), last=True)

doc1 = nlp1(u"Word01")
doc2 = nlp1(u"Word02")
## MemoryError here:
print(doc1.similarity(doc2))

doc1 = nlp2(u"A")
doc2 = nlp2(u"B")
print(doc1.similarity(doc2))
```

Here's the traceback I'm seeing
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "doc.pyx", line 367, in spacy.tokens.doc.Doc.similarity
  File "miniconda3/envs/py37/lib/python3.7/site-packages/wmd/__init__.py", line 652, in compute_similarity
    return libwmdrelax.emd(w1, w2, dists)
MemoryError: failed to allocate the cache
```

I can hack together an alphabet-only "encoding" of my vocabulary without too much effort, but I figured I would report the issue anyway just in case this isn't a spacy error.

e.g.
```
 'Word01' in nlp1.vocab
```
reports `True` as expected.

data:
[word2vec.txt](https://github.com/src-d/wmd-relax/files/3086653/word2vec.txt)
[word2vec2.txt](https://github.com/src-d/wmd-relax/files/3086685/word2vec2.txt)

**Comment by vmarkovtsev** [comment]
Thanks for such a great bug report, I am going to investigate this week.

**Comment by vmarkovtsev** [comment]
I was able to reproduce. The immediate reason is that w1, w2 and dists are all empty arrays.

**Comment by vmarkovtsev** [comment]
doc1 and doc2 are empty, too

**Comment by vmarkovtsev** [comment]
Those are empty because `is_alpha` is `False` here:

```python
for t in doc:
    print(t, t.is_alpha)
```

**Comment by vmarkovtsev** [comment]
So I am going to add a check for empty input and return 1, though I have no idea why `is_alpha` is `False`, I guess to the custom model. Changing the code like this also works:

```python
nlp1.add_pipe(wmd.WMD.SpacySimilarityHook(nlp1, only_alpha=False), last=True)
nlp2.add_pipe(wmd.WMD.SpacySimilarityHook(nlp2, only_alpha=False), last=True)
```

**Comment by zdk123** [comment]
fantastic, thanks!
