### ISSUE TITLE
Working with pre-trained fastText model

### ISSUE THREAD

**Issue by deakkon** [src-d/wmd-relax#52]
Hi all,

thank you for the lib; its quite neat and fast (as compared to other available). 

Theres an issue I encountered while working with pretrained fastText model (available [here](https://ftp.ncbi.nlm.nih.gov/pub/lu/Suppl/BioSentVec/BioWordVec_PubMed_MIMICIII_d200.bin)). 

As the OOVs in fastText model get an index -1, and your lib typecasts all word indices to an unsigned int value. -1 then get converted in to 18446744073709551615 which, naturally, isnt in the vocabulary of the model. This, finally, produces an error. 

I implemented a wrapper for the fastText model I am using (based on the example you made available): 

```
class FastTextEmbeddings(object):
    def __getitem__(self, item):
        return ftModel.get_input_vector(item)
```

My workaround is as follows (in wmd/__init__.py):

```
                class WrappedEmbeddings(object):
                    def __init__(self, items):
                        self.items = items

                    def __getitem__(self, item):
                        if not hasattr(item, "__iter__") or \
                                isinstance(item, (str, bytes)):
                            return self.items[item]
                        tmp_list = []
                        for i in item:
                            try:
                                tmp_list.append(self.items[i])
                            except:
                                tmp_list.append(self.items[-1])
                        # return numpy.array([self.items[i] for i in item], dtype=numpy.float32)
                        return numpy.array(tmp_list, dtype=numpy.float32)
```

I can confirm this code is working, but was wandering if theres an easier way, one that does not require changing your base code, to make the lib work with fastText automatically (e.g. a better FastTextEmbeddings class or similar)?

**Comment by vmarkovtsev** [comment]
Hi @deakkon 

Yep, no need to change the internals.

```python
class FastTextEmbeddings(object):
    def __getitem__(self, item):
        item = numpy.array(item, copy=True)
        item[item > len(ftModel)] = -1
        return ftModel.get_input_vector(item)
```

where `len(ftModel)` is the size of your model - number of embeddings.

**Comment by petulla** [comment]
@deakkon Do you have a recent code snippet? This fails with the latest version of fasttext.
