### ISSUE TITLE
Linux installation issue

### ISSUE THREAD

**Issue by me-emi** [src-d/wmd-relax#59]
Hi guys,

I worked with WMD one month ago and it worked perfectly on Linux. I didn't change anything on my side since then, however, WMD doesn't work now https://imgur.com/2AkA8hb. Can you tell me what's happening?

Thanks in advance,
Best,
E

**Comment by vmarkovtsev** [comment]
The quality of the image is really bad. You can drag and drop images directly to the issue, they will be attached online.

If I correctly decoded the super blurry text, you are missing `Python.h`. That has nothing to do with wmd-relax. This is a very generic problem, `apt install python3-dev`. Anyway, I cannot consult on fixing broken environments, sorry. I can only help with fixing bugs in the project.

**Comment by me-emi** [comment]
Dear Mr. @vmarkovtsev - thank you for your explanation. To be fair, I need to admit that I'm new to this, so when I consulted with a more experienced friend, he suggested that it might be something on your side, so I needed to check. Thank you for your kind explanation, I will try to do what you suggested and explore the issue further. Please continue with your work, it helped a lot of us :)
Best,
E
