### ISSUE TITLE
IndexError: arrays used as indices must be of integer (or boolean) type

### ISSUE THREAD

**Issue by nokados** [src-d/wmd-relax#62]
### Traceback
This error has the next traceback:
```
File "/home/nokados/classifiers/env/lib/python3.6/site-packages/wmd/__init__.py", line 546, in nearest_neighbors
    for (_, i2) in queue[:k]]
  File "/home/nokados/classifiers/env/lib/python3.6/site-packages/wmd/__init__.py", line 546, in <listcomp>
    for (_, i2) in queue[:k]]
  File "/home/nokados/classifiers/env/lib/python3.6/site-packages/wmd/__init__.py", line 438, in _WMD_batch
    evec = self.embeddings[joint]
IndexError: arrays used as indices must be of integer (or boolean) type
```

### Environment
Python==3.6.5
numpy==1.16.3
wmd==1.3.1
GNU/Linux Debian 9.4

### What I do?
I pass a list of ints to the function `nearest_neighbors`, as a first argument.

### What is going on?
In `_common_vocabulary_batch` there is the next line of code:
``` python
joint, index = numpy.unique(numpy.concatenate((words1, words2)),
                                    return_index=True)
```
Here,
- `words1` is my list of ints
- `words2` is an identical numpy array with **dtype='uint64'**
And after that,
`joint` has dtype equals **float64** ! 

It's strange, but if set dtype of the second numpy array to another int type (uint32 or int64), it works properly. 

So, can you explicitly cast joint to int type?

**Comment by vmarkovtsev** [comment]
Thanks for reporting this! I will add `dtype` annotations, yes.

**Comment by vmarkovtsev** [comment]
Please ping here if the problem is not healed in 1.3.2.
