### ISSUE TITLE
Suport for oov tokens

### ISSUE THREAD

**Issue by m4nuC** [src-d/wmd-relax#65]
When using FastText, as suggested in #52,  oov will have an index of -1 even though the embedding service is able to provide a vector for them and a distance metric between 2 oov vectors may still make sense.

Could you see a way around that? I am assuming that you are specifically using integer indices (rather than word tokens) for performance reason?

**Comment by vmarkovtsev** [comment]
Yes, this is for better performance and nailed hard to the internals. I can suggest searching over the vocabulary around the oov vector and supplying the nearest index found. Something like `numpy.argmin(embedded_vocabulary_matrix.dot(voc_vec))`.

**Comment by m4nuC** [comment]
Yes, that'll work. Thanks @vmarkovtsev.

**Comment by petulla** [comment]
@m4nuC Could you share how you made this work? I'm trying to do the same thing.

**Comment by m4nuC** [comment]
@petulla something like this:

```
    def get_word_id(self, word):
        if word in fasttext_model.wv.vocab:
            index = fasttext_model.wv.vocab[word].index
        # Out of voc
        else:
            nearest_matches = fasttext_model.wv.most_similar(word)
            index = fasttext_model.wv.get_vector(nearest_matches[0][0])
        return index
```
