### ISSUE TITLE
install  

### ISSUE THREAD

**Issue by wuxiaobo** [src-d/wmd-relax#7]
os:redhat 
error: Python 3.5.1 (default, Sep 13 2016, 18:48:37) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wmd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wuxiaobo/py3_env/local/lib/python3.5/site-packages/wmd/__init__.py", line 11, in <module>
    import libwmdrelax
ImportError: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/wuxiaobo/py3_env/local/lib/python3.5/site-packages/libwmdrelax.cpython-35m-x86_64-linux-gnu.so)
#######################################3
and install  Building from source

[wuxiaobo@ip-172-31-13-211 wmd-relax]$ cmake -D CMAKE_BUILD_TYPE=Release .
-- The C compiler identification is GNU 4.8.3
-- The CXX compiler identification is GNU 4.8.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Found PythonInterp: /home/wuxiaobo/py3_env/bin/python3 (found suitable version "3.5.1", minimum required is "3") 
-- Found PythonLibs: /usr/lib64/libpython3.5m.so (found suitable version "3.5.1", minimum required is "3") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wuxiaobo/soft/wmd-relax-master/wmd-relax
(py3_env) [wuxiaobo@ip-172-31-13-211 wmd-relax]$ make -j
Scanning dependencies of target wmdrelax
[ 14%] [ 42%] [ 42%] [ 57%] [ 71%] [ 85%] Building CXX object CMakeFiles/wmdrelax.dir/or-tools/src/graph/max_flow.cc.o
Building CXX object CMakeFiles/wmdrelax.dir/or-tools/src/graph/min_cost_flow.cc.o
Building CXX object CMakeFiles/wmdrelax.dir/or-tools/src/base/sysinfo.cc.o
Building CXX object CMakeFiles/wmdrelax.dir/or-tools/src/base/stringprintf.cc.o
Building CXX object CMakeFiles/wmdrelax.dir/or-tools/src/base/logging.cc.o
Building CXX object CMakeFiles/wmdrelax.dir/or-tools/src/util/stats.cc.o
[100%] Building CXX object CMakeFiles/wmdrelax.dir/python.cc.o
In file included from /home/wuxiaobo/soft/wmd-relax-master/wmd-relax/python.cc:11:0:
/home/wuxiaobo/soft/wmd-relax-master/wmd-relax/emd.h:89:0: error: ignoring #pragma omp simd [-Werror=unknown-pragmas]
   #pragma omp simd
 ^
/home/wuxiaobo/soft/wmd-relax-master/wmd-relax/emd.h:118:0: error: ignoring #pragma omp simd [-Werror=unknown-pragmas]
   #pragma omp simd
 ^
/home/wuxiaobo/soft/wmd-relax-master/wmd-relax/emd.h:125:0: error: ignoring #pragma omp simd [-Werror=unknown-pragmas]
   #pragma omp simd
 ^
/home/wuxiaobo/soft/wmd-relax-master/wmd-relax/emd.h:161:0: error: ignoring #pragma omp simd [-Werror=unknown-pragmas]
   #pragma omp simd
 ^
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/wmdrelax.dir/python.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/wmdrelax.dir/all] Error 2
make: *** [all] Error 2

**Comment by vmarkovtsev** [comment]
GCC 4.8 does not support OpenMP 4 and was not tested (very outdated). Quick fix; comment these pragmas out. Proper fix: check openmp version and surrounds pragmas with ifdefs, like here: https://github.com/src-d/lapjv/blob/master/lap.h#L235

**Comment by wuxiaobo** [comment]
thanks
